import { menuList } from "../interfaces/commandList"
export const CommandList = {
    _main: {
        main: "!main",
    },
    _generals: {
        botON: {
            x: "!bot on",
            props:{
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
            onlyForUsers: []}
            
        },
        botOff: {
            x: "!bot off",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
            onlyForUsers: [],
        },
        testNmae: {
            x: "!_test",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        Everyone: {
            x: "!everyone",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        testGay: {
            x: "!test_gay",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        }
    },
    _search: {
        LyricSearch: {
            x: "!lyricSearch",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        GetLyric: {
            x: "!getLyric",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        GlySearch: {
            x: "!GLYSearch",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        Pokemon: {
            x: "!Pokemon",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        Pinterest: {
            x: "!pinterest",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        ImgByBing: {
            x: "!img_Bing",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        ImgByGoogle: {
            x: "!img",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        TikTokSearch: {
            x: "!tik_tok",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
    },
    _media: {
        TTS: {
            x: "!tts",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        Video: {
            x: "!videos",
            IsDesabilited: true,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
    },
    _AI: {
        chatgpt: {
            x: "!chatgpt",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        Bingchat: {
            x: "!BingChat",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        gpt4: {
            x: "!gpt-4",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        Gemini: {
            x: "!Gemini",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        Simi: {
            x: "!simi",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
    },
    _Anime: {
        neko: {
            x: "!neko",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        loli: {
            x: "!loli",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        foxgirl: {
            x: "!foxgirl",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        lolipc: {
            x: "!lolipc",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
    },
    _nsfw: {
        china: {
            x: "!Asian",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        japan: {
            x: "!Japan",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        boobs: {
            x: "!Boobs",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        girls: {
            x: "!Pack",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        rule34: {
            x: "!Rule34",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
    },
    _tools: {
        stickerCrate: {
            x: "!sticker",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        EmojiFusion: {
            x: "!emojiFusion",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
        Universe: {
            x: "!universe",
            IsDesabilited: false,
            onlyAdmin: false,
            onlyGroups: false,
            onlForGroupsAdmin: false,
            restrictedUsers: [],
            restrictedGroups: [],
        },
    }
}

